[package]
name = "ch08_array_string"
version = "0.1.0"
authors = ["dxx <dx1898@foxmail.com>"]
edition = "2021"

[dependencies]
getopts = "0.2"
zip = { version = "0.5", default-features = false, features = ["deflate"] }
once_cell = "1.10.0"
